### ISSUE TITLE
RDFMappingException előhívása

### ISSUE THREAD

**Issue by gapeti29** [BME-MIT-IET/studentRepository-iet-2019#17]
Teszteljünk egy olyan osztályba tartozó objektum létrehozását RDF formátumból, aminek nincsen paraméter nélküli konstruktora. Ekkor az RDFMapper-nek RDFMappingException-t kell dobnia, azon belül NoSuchMethodException-t.

**Comment by BakaiIstvan** [comment]
Pl. az RDFMapper osztály 334. sorában sikerült az új tesztekkel előhívni egy RDFMappingException-t és egyben növelni a tesztek kódlefedettségét.

**Comment by latinovitsantal** [comment]
A unittest branch tartalmazza  a tesztesetet, amely ezt ellenőrzi
